name: push to codecommit

on:
  workflow_dispatch:
    inputs:
      artifact_url:
        type: string
        required: true
        default: 'default content'
jobs:
  push-to-codecommit:
    runs-on: ubuntu-latest
    steps:
    - name: install aws cli
      shell: bash
      run: |
        sudo apt install awscli -y
        aws --version
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Update codecommit repo
      run: |
        REPO_NAME="test-repo"
        BRANCH="main"
        echo '{ "asset_urls": ["${{ inputs.artifact_url }}"] }' | base64 | tee -a manifest.json
        ls -ltr
        cat manifest.json
        echo "getting parent commit ID: "
        commitId=$(aws codecommit get-branch --repository-name ${REPO_NAME} --branch-name ${BRANCH} | jq -r .branch.commitId)
        aws codecommit put-file \
        --repository-name ${REPO_NAME} \
        --branch-name ${BRANCH} \
        --file-content file://manifest.json \
        --file-path manifest.json \
        --parent-commit-id ${commitId} \
        --name "Harpreet Singh" \
        --email "harrylubana14@gmail.com" \
        --commit-message "updated content"
        if [[ $? -eq 0 ]];then echo "Codecommit repo updated successfully.";fi
    
